# -*- coding: utf-8 -*-
__author__ = 'm4tuu'


CATEGORIA_IVA = ((1, u"Responsable Inscripto"),
                 (2, u"Responsable no Inscripto"),
                 (3, u"No Responsable"),
                 (4, u"Exento"),
                 (5, u"Consumidor Final"),
                 (6, u"Monotributo"),
                 (7, u"Sujeto no categorizado"),
                 (8, u"Proveedor del Exterior"),
                 (9, u"Cliente del Exterior"),
                 (10, u"IVA Liberado - Ley Nº 19.640"),
                 (11, u"Responsable Inscripto – Agente de Percepción"),
                 (12, u"Pequeño Contribuyente Eventual"),
                 (13, u"Monotributista Social"),
                 (14, u"Pequeño Contribuyente Eventual Social"),
                 (15, u"IVA No Alcanzado"),)

TIPO_COMPROBANTE = ((1, u'Factura A'),
                    (2, u'Nota de Débito A'),
                    (3, u'Nota de Crédito A'),
                    (4, u'Recibo A'),
                    (6, u'Factura B'),
                    (7, u'Nota de Débito B'),
                    (8, u'Nota de Crédito B'),
                    (9, u'Recibo B'),
                    (11, u'Factura C'),
                    (12, u'Nota de Débito C'),
                    (13, u'Nota de Crédito C'),
                    (15, u'Recibo C'),)

CONCEPTO = ((1, u"Productos"),
            (2, u"Servicios"),
            (3, u"Productos y Servicios"),)

FORMA_PAGO = ((1, u"Contado"),
              (2, u"Tarjeta de Débito"),
              (3, u"Tarjeta de Crédito"),
              (4, u"Cuenta Corriente"),
              (5, u"Cheque"),
              (6, u"Ticket"),
              (7, u"Otra"),)

TIPO_DOCUMENTO = ((80, "CUIT"),
                  (86, "CUIL"),
                  (87, "CDI"),
                  (89, "LE"),
                  (90, "LC"),
                  (91, "CI Extranjera"),
                  (94, "Pasaporte"),
                  (96, "DNI"),
                  (99, "Doc. (Otro)"),)

OLICUOTA_IVA = ((3,	0),
                (4,	10.5),
                (5,	21),
                (6,	27),
                (8,	5),
                (9,	2.5),)

MONEDA = (
    ('PES', u"Peso Argentino"),
    ('DOL', u"Dólar Estadounidense"),
    # Lista incompleta, no se si es necesaria en esta ocación
)

TIPO_ATRIBUTO = (
    (1,	u"Impuestos nacionales"),
    (2,	u"Impuestos provinciales"),
    (3,	u"Impuestos municipales"),
    (4,	u"Impuestos Internos"),
    (99, u"Otro"),
)

PROVINCIA = (
    (0, u"Ciudad Autónoma de Buenos Aires"),
    (1, u"Buenos Aires"),
    (2, u"Catamara"),
    (3, u"Córdoba"),
    (4, u"Corrientes"),
    (5, u"Entre Ríos"),
    (6, u"Jujuy"),
    (7, u"Mendoza"),
    (8, u"La Rioja"),
    (9, u"Salta"),
    (10, u"San Juan"),
    (11, u"San Luis"),
    (12, u"Santa Fe"),
    (13, u"Santiago del Estero"),
    (14, u"Tucumán"),
    (16, u"Chaco"),
    (17, u"Chubut"),
    (18, u"Formosa"),
    (19, u"Misiones"),
    (20, u"Neuquén"),
    (21, u"La Pampa"),
    (22, u"Río Negro"),
    (23, u"Santa Cruz"),
    (24, u"Tierra del Fuego"),
)

UNIDAD = (
    (0, u"SIN DESCRIPCION"),
    (1, u"KILOGRAMO"),
    (2, u"METROS"),
    (3, u"METRO CUADRADO"),
    (4, u"METRO CUBICO"),
    (5, u"LITROS"),
    (6, u"1000 KILOWATT HORA"),
    (7, u"UNIDAD"),
    (8, u"PAR"),
    (9, u"DOCENA"),
    (10, u"QUILATE"),
    (11, u"MILLAR"),
    (12, u"MEGA U. INTER. ACT. ANTIB"),
    (13, u"UNIDAD INT. ACT. INMUNG"),
    (14, u"GRAMO"),
    (15, u"MILIMETRO"),
    (16, u"MILIMETRO CUBICO"),
    (17, u"KILOMETRO"),
    (18, u"HECTOLITRO"),
    (19, u"MEGA UNIDAD INT. ACT. INMUNG"),
    (20, u"CENTIMETRO"),
    (21, u"KILOGRAMO ACTIVO"),
    (22, u"GRAMO ACTIVO"),
    (23, u"GRAMO BASE"),
    (24, u"UIACTHOR"),
    (25, u"JGO.PQT. MAZO NAIPES"),
    (26, u"MUIACTHOR"),
    (27, u"CENTIMETRO CUBICO"),
    (28, u"UIACTANT"),
    (29, u"TONELADA"),
    (30, u"DECAMETRO CUBICO"),
    (31, u"HECTOMETRO CUBICO"),
    (32, u"KILOMETRO CUBICO"),
    (33, u"MICROGRAMO"),
    (34, u"NANOGRAMO"),
    (35, u"PICOGRAMO"),
    (36, u"MUIACTANT"),
    (37, u"UIACTIG"),
    (41, u"MILIGRAMO"),
    (47, u"MILILITRO"),
    (48, u"CURIE"),
    (49, u"MILICURIE"),
    (50, u"MICROCURIE"),
    (51, u"U.INTER. ACT. HORMONAL"),
    (52, u"MEGA U. INTER. ACT. HOR."),
    (53, u"KILOGRAMO BASE"),
    (54, u"GRUESA"),
    (55, u"MUIACTIG"),
    (61, u"KILOGRAMO BRUTO"),
    (62, u"PACK"),
    (63, u"HORMA"),
    (97, u"SEÑAS/ANTICIPOS"),
    (98, u"OTRAS UNIDADES"),
    (99, u"BONIFICACION"),
)